# Generated by Django 6.0 on 2025-12-15 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="genre",
            field=models.CharField(default="Action", max_length=100),
        ),
        migrations.AddField(
            model_name="movie",
            name="language",
            field=models.CharField(default="Hindi", max_length=100),
        ),
    ]
