# Generated by Django 6.0 on 2025-12-15 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_movie_genre_movie_language"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seat",
            name="is_booked",
        ),
        migrations.AddField(
            model_name="seat",
            name="locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="seat",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="seat",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "Available"),
                    ("locked", "Locked"),
                    ("booked", "Booked"),
                ],
                default="available",
                max_length=10,
            ),
        ),
    ]
