# Generated by Django 6.0 on 2025-12-15 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_booking_payment_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_email_sent",
            field=models.BooleanField(default=False),
        ),
    ]
